# Logistic regression

In [10]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import math
from sklearn.linear_model import LogisticRegression

In [11]:
df = pd.read_csv("../datasets/Iris.csv")
df

,Id,SepalLengthCm,SepalWidthCm,PetalLengthCm,PetalWidthCm,Species
0,1,5.1,3.5,1.4,0.2,Iris-setosa
1,2,4.9,3.0,1.4,0.2,Iris-setosa
2,3,4.7,3.2,1.3,0.2,Iris-setosa
3,4,4.6,3.1,1.5,0.2,Iris-setosa
4,5,5.0,3.6,1.4,0.2,Iris-setosa
...,...,...,...,...,...,...
145,146,6.7,3.0,5.2,2.3,Iris-virginica
146,147,6.3,2.5,5.0,1.9,Iris-virginica
147,148,6.5,3.0,5.2,2.0,Iris-virginica
148,149,6.2,3.4,5.4,2.3,Iris-virginica


In [12]:
df = df.iloc[:100 , :]
df = df.drop("Id", axis=1)
df["Species"] = df["Species"].apply(lambda x: 0 if x=="Iris-setosa" else 1)
df

,SepalLengthCm,SepalWidthCm,PetalLengthCm,PetalWidthCm,Species
0,5.1,3.5,1.4,0.2,0
1,4.9,3.0,1.4,0.2,0
2,4.7,3.2,1.3,0.2,0
3,4.6,3.1,1.5,0.2,0
4,5.0,3.6,1.4,0.2,0
...,...,...,...,...,...
95,5.7,3.0,4.2,1.2,1
96,5.7,2.9,4.2,1.3,1
97,6.2,2.9,4.3,1.3,1
98,5.1,2.5,3.0,1.1,1


In [13]:
y_train = df["Species"]
x_train = df.drop("Species", axis=1)

y_train = np.array(y_train).reshape((-1, 1))
x_train = np.array(x_train)
x_train

array([[5.1, 3.5, 1.4, 0.2],
       [4.9, 3. , 1.4, 0.2],
       [4.7, 3.2, 1.3, 0.2],
       [4.6, 3.1, 1.5, 0.2],
       [5. , 3.6, 1.4, 0.2],
       [5.4, 3.9, 1.7, 0.4],
       [4.6, 3.4, 1.4, 0.3],
       [5. , 3.4, 1.5, 0.2],
       [4.4, 2.9, 1.4, 0.2],
       [4.9, 3.1, 1.5, 0.1],
       [5.4, 3.7, 1.5, 0.2],
       [4.8, 3.4, 1.6, 0.2],
       [4.8, 3. , 1.4, 0.1],
       [4.3, 3. , 1.1, 0.1],
       [5.8, 4. , 1.2, 0.2],
       [5.7, 4.4, 1.5, 0.4],
       [5.4, 3.9, 1.3, 0.4],
       [5.1, 3.5, 1.4, 0.3],
       [5.7, 3.8, 1.7, 0.3],
       [5.1, 3.8, 1.5, 0.3],
       [5.4, 3.4, 1.7, 0.2],
       [5.1, 3.7, 1.5, 0.4],
       [4.6, 3.6, 1. , 0.2],
       [5.1, 3.3, 1.7, 0.5],
       [4.8, 3.4, 1.9, 0.2],
       [5. , 3. , 1.6, 0.2],
       [5. , 3.4, 1.6, 0.4],
       [5.2, 3.5, 1.5, 0.2],
       [5.2, 3.4, 1.4, 0.2],
       [4.7, 3.2, 1.6, 0.2],
       [4.8, 3.1, 1.6, 0.2],
       [5.4, 3.4, 1.5, 0.4],
       [5.2, 4.1, 1.5, 0.1],
       [5.5, 4.2, 1.4, 0.2],
       [4.9, 3

Сигмоида:

In [14]:
def g(z): 
    z = np.clip(z, -500, 500)
    response = 1 / (1 + np.exp(-z))
    return response

In [15]:
len(x_train)

100

### Градиент функции потерь 

In [16]:
size_of_features = x_train.shape[1]
np.random.seed(21)
w = np.random.randn(size_of_features).reshape((size_of_features,-1)) #начальные веса
alpha = 0.1 

w

array([[-0.05196425],
       [-0.11119605],
       [ 1.0417968 ],
       [-1.25673929]])

In [17]:
z = 0
iterator = 0
loss = np.zeros(size_of_features).reshape((size_of_features,-1))
prev_loss = np.zeros(size_of_features).reshape((size_of_features,-1))
while True:
    loss = np.zeros(size_of_features).reshape((size_of_features,-1))
    for i in range(len(x_train)):  # цикл подсчета градиента от loss (идем по каждой строке датафрейма (100 операций))
        z=0
        x = x_train[i]
        for j in range(size_of_features):
            z += x[j] * w[j]                # z = w1*x1 + w2*x2 + w3*x3 ...
        err = (y_train[i] - g(z))
        for j in range(size_of_features):
            loss[j] -= x[j] * err           # Подсчет градиента от функции потерь

    iterator +=1
    #if (abs(prev_loss) - abs(loss)).all() < 1e-4:
    if np.linalg.norm(loss) < 1e-4:
    #if iterator == 100:
        break
    w = w - np.dot(alpha, loss)
    prev_loss = loss
loss, iterator


(array([[6.77862190e-07],
        [3.50487012e-07],
        [1.97839622e-07],
        [4.47740657e-08]]),
 6)

In [18]:
predict = np.zeros(len(y_train)).reshape((-1, 1))
list_of_predict = list()
z_predicted = x_train.dot(w)
for i in range(len(z_predicted)):
    predict[i] = g(z_predicted[i])
    if predict[i] < 0.5:
        predict[i] = 0
    else:
        predict[i] = 1
    list_of_predict.append(predict[i])

list_of_predict = [x.item() for x in list_of_predict]
df_predict = pd.Series(list_of_predict).astype('Int64')
df_predict.value_counts()

0    50
1    50
Name: count, dtype: Int64

In [19]:
comparison = pd.DataFrame({"Actual data": df["Species"], "NUMPY predict": df_predict})
comparison.head(40)

,Actual data,NUMPY predict
0,0,0
1,0,0
2,0,0
3,0,0
4,0,0
5,0,0
6,0,0
7,0,0
8,0,0
9,0,0


## Сверим работу модели с работой LogisticRegression из sklearn

In [20]:
clf = LogisticRegression()
clf.fit(x_train, y_train)

/home/user/ML-Toolkit/venv/lib/python3.12/site-packages/sklearn/utils/validation.py:1365: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)


,"penalty penalty: {'l1', 'l2', 'elasticnet', None}, default='l2'Specify the norm of the penalty:- `None`: no penalty is added;- `'l2'`: add an L2 penalty term and it is the default choice;- `'l1'`: add an L1 penalty term;- `'elasticnet'`: both L1 and L2 penalty terms are added... warning:: Some penalties may not work with some solvers. See the parameter `solver` below, to know the compatibility between the penalty and solver... versionadded:: 0.19 l1 penalty with SAGA solver (allowing 'multinomial' + L1).. deprecated:: 1.8 `penalty` was deprecated in version 1.8 and will be removed in 1.10. Use `l1_ratio` and `C` instead. `l1_ratio=0` for `penalty='l2'`, `l1_ratio=1` for `penalty='l1'`, `l1_ratio` set to any float between 0 and 1 for `penalty='elasticnet'`, and `C=np.inf` for `penalty=None`.",'deprecated'
,"C C: float, default=1.0Inverse of regularization strength; must be a positive float.Like in support vector machines, smaller values specify strongerregularization. `C=np.inf` results in unpenalized logistic regression.For a visual example on the effect of tuning the `C` parameterwith an L1 penalty, see::ref:`sphx_glr_auto_examples_linear_model_plot_logistic_path.py`.",1.0
,"l1_ratio l1_ratio: float, default=0.0The Elastic-Net mixing parameter, with `0 <= l1_ratio <= 1`. Setting`l1_ratio=1` gives a pure L1-penalty, setting `l1_ratio=0` a pure L2-penalty.Any value between 0 and 1 gives an Elastic-Net penalty of the form`l1_ratio * L1 + (1 - l1_ratio) * L2`... warning:: Certain values of `l1_ratio`, i.e. some penalties, may not work with some solvers. See the parameter `solver` below, to know the compatibility between the penalty and solver... versionchanged:: 1.8 Default value changed from None to 0.0... deprecated:: 1.8 `None` is deprecated and will be removed in version 1.10. Always use `l1_ratio` to specify the penalty type.",0.0
,"dual dual: bool, default=FalseDual (constrained) or primal (regularized, see also:ref:`this equation <regularized-logistic-loss>`) formulation. Dual formulationis only implemented for l2 penalty with liblinear solver. Prefer `dual=False`when n_samples > n_features.",False
,"tol tol: float, default=1e-4Tolerance for stopping criteria.",0.0001
,"fit_intercept fit_intercept: bool, default=TrueSpecifies if a constant (a.k.a. bias or intercept) should beadded to the decision function.",True
,"intercept_scaling intercept_scaling: float, default=1Useful only when the solver `liblinear` is usedand `self.fit_intercept` is set to `True`. In this case, `x` becomes`[x, self.intercept_scaling]`,i.e. a ""synthetic"" feature with constant value equal to`intercept_scaling` is appended to the instance vector.The intercept becomes``intercept_scaling * synthetic_feature_weight``... note:: The synthetic feature weight is subject to L1 or L2 regularization as all other features. To lessen the effect of regularization on synthetic feature weight (and therefore on the intercept) `intercept_scaling` has to be increased.",1
,"class_weight class_weight: dict or 'balanced', default=NoneWeights associated with classes in the form ``{class_label: weight}``.If not given, all classes are supposed to have weight one.The ""balanced"" mode uses the values of y to automatically adjustweights inversely proportional to class frequencies in the input dataas ``n_samples / (n_classes * np.bincount(y))``.Note that these weights will be multiplied with sample_weight (passedthrough the fit method) if sample_weight is specified... versionadded:: 0.17 *class_weight='balanced'*",None
,"random_state random_state: int, RandomState instance, default=NoneUsed when ``solver`` == 'sag', 'saga' or 'liblinear' to shuffle thedata. See :term:`Glossary <random_state>` for details.",None
,"solver solver: {'lbfgs', 'liblinear', 'newton-cg', 'newton-cholesky', 'sag', 'saga'}, default='lbfgs'Algorithm to use in the optimization problem. Default is 'lbfgs'.To choose a solver, you might want to consider the following aspects:- 'lbfgs' is a good default sol

In [21]:
sklearn_predict = clf.predict(x_train)
comparison['sklearn predict'] = sklearn_predict

In [22]:
comparison.tail(45)

,Actual data,NUMPY predict,sklearn predict
55,1,1,1
56,1,1,1
57,1,1,1
58,1,1,1
59,1,1,1
60,1,1,1
61,1,1,1
62,1,1,1
63,1,1,1
64,1,1,1


In [23]:
numpy_error = comparison['Actual data'] - comparison['NUMPY predict']
counts_numpy_error = numpy_error[numpy_error != 0].count()

sklearn_error = comparison['Actual data'] - comparison['sklearn predict']
counts_sklearn_error = sklearn_error[sklearn_error != 0].count()

print("Количество ошибочных прогнозов модели, реализованной на NUMPY:")
print(f"{counts_numpy_error} из {len(y_train)}\n")
print("Количество ошибочных прогнозов модели, реализованной в scikit-learn:")
print(f"{counts_sklearn_error} из {len(y_train)}")

Количество ошибочных прогнозов модели, реализованной на NUMPY:
0 из 100

Количество ошибочных прогнозов модели, реализованной в scikit-learn:
0 из 100
